// Central registry of all games
export const GAMES = [
  {
    id: 'memory-match',
    title: 'Memory Match',
    emoji: '🃏',
    description: 'Flip cards and find matching pairs. Train your memory!',
    subject: 'Brain',
    gradient: 'card-gradient-purple',
    xpReward: 25,
    coinReward: 12,
    requiredCoins: 0,
    tags: ['memory', 'fun'],
  },
  {
    id: 'whack-a-mole',
    title: 'Whack-a-Mole',
    emoji: '🔨',
    description: 'Moles are popping up everywhere! Hit as many as you can!',
    subject: 'Reflex',
    gradient: 'card-gradient-orange',
    xpReward: 20,
    coinReward: 10,
    requiredCoins: 0,
    tags: ['action', 'reflex'],
  },
  {
    id: 'connect4',
    title: 'Connect 4',
    emoji: '🔴',
    description: 'Drop discs and connect 4 in a row before your opponent!',
    subject: 'Strategy',
    gradient: 'card-gradient-blue',
    xpReward: 30,
    coinReward: 15,
    requiredCoins: 0,
    tags: ['strategy', 'two-player'],
  },
  {
    id: 'quiz',
    title: 'Jeopardy Quiz',
    emoji: '❓',
    description: 'Answer trivia questions across science, math, and history!',
    subject: 'All',
    gradient: 'card-gradient-green',
    xpReward: 35,
    coinReward: 20,
    requiredCoins: 0,
    tags: ['trivia', 'learning'],
  },
  {
    id: 'snake-ladders',
    title: 'Snake & Ladders',
    emoji: '🎲',
    description: 'Roll the dice and race to the top! Watch out for snakes!',
    subject: 'Math',
    gradient: 'card-gradient-pink',
    xpReward: 20,
    coinReward: 10,
    requiredCoins: 0,
    tags: ['classic', 'dice'],
  },
  {
    id: 'snake',
    title: 'Snake',
    emoji: '🐍',
    description: 'Grow your snake by eating food. Don\'t hit the walls or yourself!',
    subject: 'Reflex',
    gradient: 'card-gradient-green',
    xpReward: 25,
    coinReward: 12,
    requiredCoins: 0,
    tags: ['classic', 'reflex', 'endless'],
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Friend',
    emoji: '🐦',
    description: 'Tap to fly through pipes. How far can you go?',
    subject: 'Reflex',
    gradient: 'card-gradient-blue',
    xpReward: 15,
    coinReward: 8,
    requiredCoins: 0,
    tags: ['action', 'endless'],
  },
  {
    id: 'puzzle',
    title: 'Puzzle Solver',
    emoji: '🧩',
    description: 'Solve sliding puzzles! Arrange tiles back to the picture.',
    subject: 'Logic',
    gradient: 'card-gradient-green',
    xpReward: 30,
    coinReward: 15,
    requiredCoins: 20,
    tags: ['puzzle', 'logic'],
  },
  {
    id: 'word-builder',
    title: 'Word Builder',
    emoji: '🔤',
    description: 'Unscramble letters to form words and boost your vocabulary!',
    subject: 'English',
    gradient: 'card-gradient-purple',
    xpReward: 30,
    coinReward: 15,
    requiredCoins: 0,
    tags: ['english', 'words'],
  },
  {
    id: 'math-blast',
    title: 'Math Blast',
    emoji: '💥',
    description: 'Solve math problems before the timer runs out! Go, go, go!',
    subject: 'Math',
    gradient: 'card-gradient-pink',
    xpReward: 35,
    coinReward: 18,
    requiredCoins: 0,
    tags: ['math', 'speed'],
  },
];

export const getGame = (id) => GAMES.find((g) => g.id === id);
